### ISSUE TITLE
용량이 가득 찼다고 나옵니다.

### ISSUE THREAD

**Issue by hslee4430** [2023-Spring-ECE4278/lab4#2]
오늘까지 숙제를 해야 해서 시뮬레이션을 해봐야 하는데. 할 수가 없습니다. 
일단 제출은 하겠습니다. 
계속 동작이 안되서 lab4를 지우고 다시 git clone하는데 
git clone https://github.com/2023-Spring-ECE4278/lab4.git
아래와 같은 에러가 나옵니다. 용량이 없다고 합니다. 
/home/SOC39/lab4/.git/refs/heads: No space left on device

용량을 봤더니 home이 100% 입니다. 
[SOC39@taurus ~]$ df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/sda3             432G  391G   19G  96% /
tmpfs                  63G   80K   63G   1% /dev/shm
/dev/sda1             380M  183M  177M  51% /boot
192.168.100.100:/semihome
                       19T  5.5T   13T  30% /semihome
192.168.100.100:/semiapps
                       19T  5.5T   13T  30% /semiapps
/dev/sdb1             458G  435G   17M 100% /home

아직 동작 확인을 못했습니다.

**Comment by hslee4430** [comment]
오늘 아침에 다시 해보니 되네요... ㅠㅠ 
이유는...잘 모르겠습니다.

**Comment by Park-So-Young** [comment]
네, 확인해보았는데 현재 56%로 문제 없는 것 같습니다. 
서버 문제는 아이캠퍼스 메세지로 보내주시면, 더 빨리 확인하고 도와드리겠습니다.
